### ISSUE TITLE
Regexp still in use on Cyberdojo

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-ltd/shouty.rb#4]
Doesn't seem to be uptodate with this repo

**Comment by sebrose** [comment]
The Cyber-Dojo code for all Shouty and Testable Architecture is in a separate repo - cucumber-ltd/cyber-dojo-start-points-custom.git

**Comment by sebrose** [comment]
Updated by this [commit](https://github.com/cucumber-ltd/cyber-dojo-start-points-custom/commit/c50778578d1930601932eed65bb68ab067f6442b)
